'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { geoArea, geoCentroid, geoDistance, geoGraticule10, geoNaturalEarth1, geoOrthographic, geoPath } from 'd3-geo';
import { POLITY_TRANSITION_YEARS, TERRITORY_MAX_YEAR, TERRITORY_MIN_YEAR, territoryPeriodAt } from './territoryChronology';
import { TERRITORY_PLACES } from './territoryPlaces';
import styles from './territory-globe.module.css';

const sphere = { type: 'Sphere' };
const graticule = geoGraticule10();
const MAX_FEATURE_AREA = 2.2;
const PALETTE = ['#566451','#685d4c','#496561','#694f4d','#536a55','#5b5365','#70684a','#475d55','#685b4d'];
const RU = { Russia:'Россия',US:'США',USA:'США',Canada:'Канада',Greenland:'Гренландия',Iceland:'Исландия',Norway:'Норвегия',Sweden:'Швеция',Finland:'Финляндия',Denmark:'Дания',Poland:'Польша',Germany:'Германия',France:'Франция',Italy:'Италия',Spain:'Испания',UK:'Великобритания',Ireland:'Ирландия',Belarus:'Беларусь',Ukraine:'Украина',Lithuania:'Литва',Latvia:'Латвия',Estonia:'Эстония',Georgia:'Грузия',Armenia:'Армения',Azerbaijan:'Азербайджан',Kazakhstan:'Казахстан',China:'Китай',Mongolia:'Монголия',India:'Индия',Pakistan:'Пакистан',Afghanistan:'Афганистан',Iran:'Иран',Iraq:'Ирак',Turkey:'Турция',Syria:'Сирия',Egypt:'Египет',Japan:'Япония',Korea:'Корея','Golden Horde':'Золотая Орда',Novgorod:'Новгород',Muscovy:'Москва','Grand Duchy of Moscow':'Московское княжество',Byzantium:'Византия','Ottoman Empire':'Османская империя','Polish-Lithuanian Commonwealth':'Речь Посполитая','Grand Duchy of Lithuania':'Великое княжество Литовское' };

const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const yearPart=v=>{const m=String(v??'').match(/-?\d{3,4}/);return m?Number(m[0]):null;};
const reverseRing=r=>[...r].reverse();
function normalizeFeature(f){
  if(!f?.geometry||!['Polygon','MultiPolygon'].includes(f.geometry.type)) return null;
  let next=f;
  if(geoArea(next)>Math.PI*2){
    const g=next.geometry.type==='Polygon'
      ? {type:'Polygon',coordinates:next.geometry.coordinates.map(reverseRing)}
      : {type:'MultiPolygon',coordinates:next.geometry.coordinates.map(poly=>poly.map(reverseRing))};
    next={...next,geometry:g};
  }
  const a=geoArea(next);
  if(!Number.isFinite(a)||a<=0||a>MAX_FEATURE_AREA) return null;
  return next;
}
const normalizeCollection=c=>({...c,features:(c.features||[]).map(normalizeFeature).filter(Boolean)});
function featureName(f){const p=f.properties||{};return [p.ABBREVN,p.NAME,p.SUBJECTO,p.PARTOF,p.name,p.ADMIN,p.entity,p.polity].find(x=>typeof x==='string'&&x.trim())?.trim()||'';}
function featureColor(f,i){const n=featureName(f);let h=19+i;for(let k=0;k<n.length;k++)h=((h<<5)-h+n.charCodeAt(k))|0;return PALETTE[Math.abs(h)%PALETTE.length];}
function validAt(f,y){const s=yearPart(f.properties?.start_date),e=yearPart(f.properties?.end_date);return(s===null||y>=s)&&(e===null||y<=e);}
function selectRussia(c,y){if(!c?.features?.length)return[];const exact=c.features.filter(f=>validAt(f,y));if(exact.length)return exact;const prev=c.features.map(feature=>({feature,start:yearPart(feature.properties?.start_date)})).filter(x=>x.start!==null&&x.start<=y).sort((a,b)=>b.start-a.start);return prev.length?prev.filter(x=>x.start===prev[0].start).map(x=>x.feature):[];}

function useData(year,polityId){
  const [index,setIndex]=useState(null),[manifest,setManifest]=useState(null),[world,setWorld]=useState(null),[worldYear,setWorldYear]=useState(null),[russia,setRussia]=useState(null);
  const worldCache=useRef(new Map()),russiaCache=useRef(new Map());
  useEffect(()=>{const base=process.env.NEXT_PUBLIC_BASE_PATH??'',c=new AbortController();Promise.all([fetch(`${base}/data/territory/world-history/index.json`,{signal:c.signal}).then(r=>r.json()),fetch(`${base}/data/territory/archive/manifest.json`,{signal:c.signal}).then(r=>r.json())]).then(([a,b])=>{if(!c.signal.aborted){setIndex(a);setManifest(b);}}).catch(()=>{});return()=>c.abort();},[]);
  useEffect(()=>{if(!index?.snapshots?.length)return;const list=[...index.snapshots].sort((a,b)=>a.year-b.year),s=[...list].reverse().find(x=>x.year<=year)||list[0],cached=worldCache.current.get(s.file);if(cached){setWorld(cached);setWorldYear(s.year);return;}const base=process.env.NEXT_PUBLIC_BASE_PATH??'',c=new AbortController();fetch(`${base}/data/territory/world-history/${s.file}`,{signal:c.signal,cache:'force-cache'}).then(r=>r.json()).then(normalizeCollection).then(d=>{worldCache.current.set(s.file,d);if(!c.signal.aborted){setWorld(d);setWorldYear(s.year);}}).catch(()=>{});return()=>c.abort();},[index,year]);
  useEffect(()=>{const e=manifest?.polities?.find(p=>p.polity_id===polityId&&p.file&&p.features>0);if(!e?.file){setRussia(null);return;}const cached=russiaCache.current.get(e.file);if(cached){setRussia(cached);return;}const base=process.env.NEXT_PUBLIC_BASE_PATH??'',c=new AbortController();fetch(`${base}/data/territory/archive/${e.file}`,{signal:c.signal,cache:'force-cache'}).then(r=>r.json()).then(normalizeCollection).then(d=>{russiaCache.current.set(e.file,d);if(!c.signal.aborted)setRussia(d);}).catch(()=>{});return()=>c.abort();},[manifest,polityId]);
  return{index,world,worldYear,russia};
}

function texturePattern(ctx){const tile=document.createElement('canvas');tile.width=96;tile.height=96;const t=tile.getContext('2d');t.strokeStyle='rgba(237,220,171,.09)';t.lineWidth=.7;for(let y=8;y<96;y+=15){t.beginPath();for(let x=-10;x<110;x+=8){const yy=y+Math.sin((x+y)*.13)*3;x<0?t.moveTo(x,yy):t.lineTo(x,yy);}t.stroke();}t.fillStyle='rgba(255,240,190,.08)';for(let i=0;i<34;i++)t.fillRect((i*37)%96,(i*53)%96,1,1);return ctx.createPattern(tile,'repeat');}
function labelBox(l){const w=l.text.length*l.size*.56+(l.kind==='capital'?18:8),h=l.size*1.25+7,off=['capital','regional'].includes(l.kind)?w/2:0;return{l:l.x-w/2+off,r:l.x+w/2+off,t:l.y-h/2,b:l.y+h/2};}
function filteredLabels(labels,w,h,portrait){const out=[],boxes=[],top=portrait?155:90,bottom=portrait?125:95;for(const l of [...labels].sort((a,b)=>b.priority-a.priority)){const b=labelBox(l);if(b.l<12||b.r>w-12||b.t<top||b.b>h-bottom)continue;if(boxes.some(x=>!(x.r+8<b.l||x.l-8>b.r||x.b+8<b.t||x.t-8>b.b)))continue;out.push(l);boxes.push(b);}return out;}

export function HistoricalTerritoryGlobeCanvasRuntime({initialYear=TERRITORY_MAX_YEAR}){
  const sceneRef=useRef(null),canvasRef=useRef(null),frameRef=useRef(null),pointers=useRef(new Map()),pinch=useRef(null),drag=useRef({active:false,x:0,y:0,rotation:[-64,-48,0]});
  const [viewport,setViewport]=useState({width:1600,height:900}),[year,setYear]=useState(clamp(initialYear,TERRITORY_MIN_YEAR,TERRITORY_MAX_YEAR)),[viewMode,setViewMode]=useState('globe'),[rotation,setRotation]=useState([-64,-48,0]),[zoom,setZoom]=useState(1.45),[fullscreen,setFullscreen]=useState(false),[showBorders,setShowBorders]=useState(true);
  const period=territoryPeriodAt(year),{index,world,worldYear,russia}=useData(year,period.polityId),portrait=viewport.height>viewport.width*1.08,russiaFeatures=useMemo(()=>selectRussia(russia,year),[russia,year]),russiaCollection=useMemo(()=>({type:'FeatureCollection',features:russiaFeatures}),[russiaFeatures]);
  useEffect(()=>{const n=sceneRef.current;if(!n)return;const update=()=>{const r=n.getBoundingClientRect();if(r.width&&r.height)setViewport({width:Math.round(r.width),height:Math.round(r.height)});};update();const ro=new ResizeObserver(update);ro.observe(n);return()=>ro.disconnect();},[]);
  const projection=useMemo(()=>{const{width,height}=viewport;if(viewMode==='map')return geoNaturalEarth1().translate([width/2,height*(portrait?.45:.5)]).scale(Math.min(width/5.6,height/3.15)*zoom).precision(.85);const radius=portrait?Math.min(width*.48,height*.32):Math.min(width*.34,height*.46);return geoOrthographic().translate([width*(portrait?.5:.62),height*(portrait?.44:.5)]).scale(radius*zoom).rotate(rotation).clipAngle(90).precision(.95);},[viewport,viewMode,portrait,zoom,rotation]);
  const labels=useMemo(()=>{const out=[],center=[-rotation[0],-rotation[1]],mobile=portrait;if(russiaFeatures.length){const g=geoCentroid(russiaCollection),p=projection(g);if(p&&(viewMode!=='globe'||geoDistance(g,center)<Math.PI/2-.05))out.push({text:period.label,x:p[0],y:p[1],size:mobile?17:21,priority:100000,kind:'russia'});}if(world){const countries=[];for(const f of world.features){const n=featureName(f);if(!n||/russia|russian|росси/i.test(n))continue;const g=geoCentroid(f);if(viewMode==='globe'&&geoDistance(g,center)>Math.PI/2-.06)continue;const p=projection(g);if(!p)continue;const a=geoArea(f);countries.push({text:RU[n]||n,x:p[0],y:p[1],size:clamp(10+Math.sqrt(a)*8,mobile?11:12,mobile?15:19),priority:1000+a*10000,kind:'country'});}countries.sort((a,b)=>b.priority-a.priority);out.push(...countries.slice(0,mobile?(zoom<2?7:zoom<3?11:16):22));}const places=[];for(const p of TERRITORY_PLACES){if((p.from??TERRITORY_MIN_YEAR)>year||(p.to??TERRITORY_MAX_YEAR)<year)continue;if(mobile&&p.kind==='regional'&&zoom<2.8)continue;if(!mobile&&p.kind==='regional'&&zoom<1.8)continue;if(viewMode==='globe'&&geoDistance([p.lon,p.lat],center)>Math.PI/2-.06)continue;const q=projection([p.lon,p.lat]);if(!q)continue;places.push({text:p.name,x:q[0],y:q[1],size:p.kind==='capital'?(mobile?11:12):10,priority:p.kind==='capital'?700:250,kind:p.kind});}places.sort((a,b)=>b.priority-a.priority);out.push(...places.slice(0,mobile?(zoom<2?4:zoom<3?8:18):34));return filteredLabels(out,viewport.width,viewport.height,portrait);},[world,year,zoom,projection,rotation,portrait,viewMode,russiaFeatures.length,russiaCollection,period.label,viewport]);
  const draw=useCallback(()=>{const canvas=canvasRef.current;if(!canvas)return;const{width,height}=viewport,dpr=Math.min(window.devicePixelRatio||1,portrait?1.3:1.7);if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;}const ctx=canvas.getContext('2d',{alpha:true});ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const path=geoPath(projection,ctx),ocean=ctx.createRadialGradient(width*.38,height*.28,10,width*.52,height*.48,Math.max(width,height)*.7);ocean.addColorStop(0,'#173b48');ocean.addColorStop(.5,'#08232e');ocean.addColorStop(1,'#020c12');ctx.beginPath();path(sphere);ctx.fillStyle=viewMode==='globe'?ocean:'#07171e';ctx.fill();ctx.beginPath();path(graticule);ctx.strokeStyle='rgba(177,200,194,.09)';ctx.lineWidth=.55;ctx.stroke();
    const land=document.createElement('canvas');land.width=canvas.width;land.height=canvas.height;const lc=land.getContext('2d');lc.setTransform(dpr,0,0,dpr,0,0);const lp=geoPath(projection,lc);(world?.features||[]).forEach((f,i)=>{lc.beginPath();lp(f);lc.fillStyle=featureColor(f,i);lc.fill();if(showBorders){lc.strokeStyle='rgba(233,220,188,.44)';lc.lineWidth=.55;lc.stroke();}});const pat=texturePattern(lc);if(pat){lc.globalCompositeOperation='source-atop';lc.fillStyle=pat;lc.fillRect(0,0,width,height);const shade=lc.createLinearGradient(0,0,width,height);shade.addColorStop(0,'rgba(255,236,181,.15)');shade.addColorStop(.48,'rgba(255,255,255,0)');shade.addColorStop(1,'rgba(0,0,0,.28)');lc.fillStyle=shade;lc.fillRect(0,0,width,height);lc.globalCompositeOperation='source-over';}ctx.drawImage(land,0,0,width,height);
    if(russiaFeatures.length){ctx.beginPath();path(russiaCollection);ctx.fillStyle='#34563a';ctx.fill();ctx.strokeStyle='#e2c56f';ctx.lineWidth=.9;ctx.stroke();ctx.save();ctx.clip();const rg=ctx.createLinearGradient(width*.25,height*.24,width*.78,height*.78);rg.addColorStop(0,'rgba(211,215,142,.18)');rg.addColorStop(.48,'rgba(52,92,58,.02)');rg.addColorStop(1,'rgba(0,0,0,.28)');ctx.fillStyle=rg;ctx.fillRect(0,0,width,height);ctx.restore();}
    if(viewMode==='globe'){ctx.beginPath();path(sphere);ctx.strokeStyle='rgba(227,209,159,.62)';ctx.lineWidth=.9;ctx.stroke();}
    ctx.textBaseline='middle';for(const l of labels){if(l.kind==='capital'){ctx.fillStyle='#f7e5ae';ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?2.4:5.2,x=l.x+Math.cos(a)*r,y=l.y+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();}else if(l.kind==='regional'){ctx.beginPath();ctx.arc(l.x,l.y,2.2,0,Math.PI*2);ctx.fillStyle='#f2e5bd';ctx.fill();}ctx.font=`${l.kind==='russia'?500:400} ${l.size}px Georgia, 'Times New Roman', serif`;ctx.textAlign=['capital','regional'].includes(l.kind)?'left':'center';const tx=l.x+(l.kind==='capital'?8:l.kind==='regional'?6:0);ctx.lineWidth=l.kind==='russia'?3:2;ctx.strokeStyle='rgba(3,10,13,.78)';ctx.strokeText(l.text,tx,l.y);ctx.fillStyle=l.kind==='russia'?'#f3e6be':'#eee4cb';ctx.fillText(l.text,tx,l.y);}},[viewport,portrait,projection,world,russiaFeatures.length,russiaCollection,showBorders,viewMode,labels]);
  useEffect(()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current);frameRef.current=requestAnimationFrame(draw);return()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current);};},[draw]);
  const focusRussia=useCallback(()=>{const[lon,lat]=period.focus;setRotation([-lon,-lat,0]);setZoom(viewMode==='globe'?1.45:1.12);},[period.focus,viewMode]);useEffect(()=>{focusRussia();},[period.polityId]);useEffect(()=>{const h=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',h);return()=>document.removeEventListener('fullscreenchange',h);},[]);
  const zoomBounds=viewMode==='globe'?[.9,9]:[.75,7],changeZoom=d=>setZoom(z=>clamp(z+d,zoomBounds[0],zoomBounds[1]));
  const down=e=>{e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const a=[...pointers.current.values()];if(a.length>=2){pinch.current={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom};drag.current.active=false;return;}drag.current={active:true,x:e.clientX,y:e.clientY,rotation};};
  const move=e=>{if(!pointers.current.has(e.pointerId))return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const a=[...pointers.current.values()];if(a.length>=2){const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(!pinch.current)pinch.current={d,zoom};setZoom(clamp(pinch.current.zoom*d/Math.max(24,pinch.current.d),zoomBounds[0],zoomBounds[1]));return;}if(!drag.current.active||viewMode!=='globe')return;const dx=e.clientX-drag.current.x,dy=e.clientY-drag.current.y,s=.16/zoom,next=[drag.current.rotation[0]+dx*s,clamp(drag.current.rotation[1]-dy*s,-78,78),0];if(frameRef.current)cancelAnimationFrame(frameRef.current);frameRef.current=requestAnimationFrame(()=>setRotation(next));};
  const up=e=>{pointers.current.delete(e.pointerId);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(pointers.current.size<2)pinch.current=null;drag.current.active=false;};
  const snapshots=useMemo(()=>{const ys=new Set(POLITY_TRANSITION_YEARS);for(const s of index?.snapshots||[])ys.add(s.year);ys.add(TERRITORY_MAX_YEAR);return[...ys].filter(y=>y>=TERRITORY_MIN_YEAR&&y<=TERRITORY_MAX_YEAR).sort((a,b)=>a-b);},[index]);const jump=dir=>{const a=dir>0?snapshots.filter(y=>y>year):snapshots.filter(y=>y<year).reverse();if(a.length)setYear(a[0]);};const toggleFullscreen=async()=>{if(!sceneRef.current)return;document.fullscreenElement?await document.exitFullscreen():await sceneRef.current.requestFullscreen();};
  return <main className={`${styles.page} premiumTerritoryPage`}><section ref={sceneRef} className={`${styles.scene} premiumTerritoryScene`}><div className={styles.space}/><canvas ref={canvasRef} className={`${styles.globe} ${styles.globeInteractive}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onWheel={e=>{e.preventDefault();changeZoom(e.deltaY>0?-.28:.28);}}/><header className={styles.topbar}><div className={styles.brand}><span className={styles.brandSymbol}>Р</span><div><strong>Правители России</strong><span>Исторический глобус</span></div></div><div className={styles.topControls}><div className={styles.segmented}><button className={viewMode==='globe'?styles.active:''} onClick={()=>setViewMode('globe')}>Глобус</button><button className={viewMode==='map'?styles.active:''} onClick={()=>setViewMode('map')}>Карта</button></div><button className={styles.controlButton} onClick={focusRussia}>К России</button><button className={styles.controlButton} onClick={toggleFullscreen}>{fullscreen?'Свернуть':'На весь экран'}</button></div></header><aside className={styles.story}><div className={styles.eyebrow}>{period.era}</div><div className={styles.storyRow}><h1>{period.label}</h1><span className={styles.storyYear}>{year}</span></div><p>Исторический мировой срез {worldYear??'—'} года · локальная база исторических границ.</p></aside><div className={styles.mapTools}><button onClick={()=>changeZoom(.45)}>+</button><button onClick={()=>changeZoom(-.45)}>−</button><button onClick={()=>setShowBorders(v=>!v)} className={showBorders?styles.toolActive:''}>◎</button></div><section className={styles.timeline}><div className={styles.timelineTop}><button onClick={()=>jump(-1)}>‹</button><div><strong>{period.shortLabel}</strong><span>{TERRITORY_MIN_YEAR} — {TERRITORY_MAX_YEAR}</span></div><div className={styles.timelineCurrent}>{year}</div><button onClick={()=>jump(1)}>›</button></div><div className={styles.rangeRow}><span>{TERRITORY_MIN_YEAR}</span><div className={styles.rangeTrack}><input type='range' min={TERRITORY_MIN_YEAR} max={TERRITORY_MAX_YEAR} value={year} onChange={e=>setYear(clamp(Number(e.target.value),TERRITORY_MIN_YEAR,TERRITORY_MAX_YEAR))}/><div className={styles.marks}>{snapshots.map(v=><i key={v} style={{left:`${((v-TERRITORY_MIN_YEAR)/(TERRITORY_MAX_YEAR-TERRITORY_MIN_YEAR))*100}%`}}/>)}</div></div><span>{TERRITORY_MAX_YEAR}</span></div></section></section></main>;
}
